const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const page = fs.readFileSync(path.join(__dirname, '../src/pages/reports/AiReportsPage.tsx'), 'utf8')

test('product card source preserves movement period meaning and excludes V1 fields', () => {
  assert.match(page, /subject === 'productCards'/)
  assert.match(page, /Stok satırı olmayan kartlar da dahildir/)
  assert.match(page, /Dönem hareket tarihine uygulanır; kart açılışı ayrı filtredir/)
  assert.match(page, /dynamicPlan.cardWindowMonths/)
  assert.match(page, /gözlem süresi tamamlanmamış kartlar dışarıda kalır/)
  assert.match(page, /!f.id.startsWith\('cards\.'\)/)
  assert.match(page, /!f.id.startsWith\('cardMovements\.'\)/)
})

test('staff source requires staff/domain rights and describes activity rather than invented performance', () => {
  assert.match(page, /hasPermission\('iam.users.view'\)/)
  assert.match(page, /subject === 'staffActivities'/)
  assert.match(page, /Personel işlem kayıtları/)
  assert.match(page, /Panel faturaları otomatik oluşturulanları da içerir/)
  assert.match(page, /!f.id.startsWith\('staff\.'\)/)
})

test('customer activity selection does not relabel all-period counts as matched counts', () => {
  assert.match(page, /İlişkili sipariş koşulları müşteri listesini süzer/)
  assert.match(page, /yalnız eşleşen işlemleri değil, dönemdeki tüm yetkili kayıtları sayar/)
})

test('dynamic metadata is unique and manual V1 recipes use only the legacy dictionary', () => {
  assert.match(page, /new Map\(rawFields\.map\(field => \[field\.id, field\]\)\)/)
  assert.match(page, /metrics: manualFields\.filter/)
  assert.match(page, /manualFields\.filter\(f => f\.kind === 'dimension'\)\.map/)
})

test('report prompt and introduction are not restricted to stock wording', () => {
  assert.match(page, /Nasıl bir rapor hazırlamak istiyorsunuz\?/)
  assert.doesNotMatch(page, /Nasıl bir stok raporu|Stok raporu hazırlığı/)
  assert.match(page, /Yanıtınızı veya raporda istediğiniz değişikliği yazın/)
})

test('AI report is guarded before editor mounts and state is per user', () => {
  assert.ok(page.indexOf("!hasPermission('inventory.view')") < page.indexOf('<ReportEditor'))
  assert.match(page, /<ReportEditor key=\{userId\}/)
  assert.match(page, /queryKey: \['ai-report-catalog', userId\]/)
})
test('report is explicit-submit, no fake AI or automatic query execution', () => {
  assert.match(page, /run.mutate\(recipe\)/)
  assert.match(page, /Doğal dil ile AI yorumlama henüz bağlı değil/)
  assert.match(page, /disabled=\{!catalog.data\?\.enabled/)
  assert.doesNotMatch(page, /api\.openai|apiKey|localStorage/)
})
test('stale result is hidden on input change or failure; shared DataGrid used', () => {
  assert.match(page, /run.data\?\.recipe === recipe/)
  assert.match(page, /!run.isError && !catalog.isError/)
  assert.match(page, /<DataGrid<Row>/)
  assert.doesNotMatch(page, /export=|\.reduce\(/)
})
test('grid queries the server after explicit submission, never slices a partial result', () => {
  assert.match(page, /enabled: submitted\?\.recipe === recipe/)
  assert.match(page, /api.post\('\/reports\/ai\/grid'/)
  assert.match(page, /queryKey: \['ai-report-grid', userId, submitted, grid.state\]/)
  assert.match(page, /sortable: !\(id === 'orders.count'/)
  assert.match(page, /totalCount=\{result\?\.totalCount/)
  assert.match(page, /rows=\{rows\}/)
  assert.match(page, /submitted\?\.recipe !== recipe/)
  assert.doesNotMatch(page, /rows\.slice|rows\.filter|rows\.sort/)
  const query = page.slice(page.indexOf('const reportQuery'), page.indexOf('const interpret'))
  assert.doesNotMatch(query, /interpret|openai/i)
})
test('interpretation requires explicit confirmation and never automatically runs', () => {
  assert.match(page, /transmissionConfirmed: consent/)
  assert.match(page, /setConsent\(false\)/)
  assert.match(page, /!catalog.data\?\.naturalLanguageEnabled/)
  assert.match(page, /if \(data.status === 'ready' && data.definition\) setProposal\(data.definition\)/)
  assert.match(page, /Otomatik kontrol tüm kişisel bilgileri tespit edemez/)
})
test('sole authorized AI account is automatic; multiple accounts require a choice', () => {
  assert.match(page, /queryKey: \['ai-report-firms', userId\]/)
  assert.match(page, /const \[selectedFirmId, setFirmId\] = useState\(''\)/)
  assert.match(page, /setFirmId\(e.target.value\); setConsent\(false\); setProposal\(null\)/)
  assert.match(page, /\|\| !firmAvailable/)
  assert.match(page, /transmissionConfirmed: consent, firmId,/)
  assert.match(page, /firms\.data\?\.length === 1 \? firms\.data\[0\]\.id : selectedFirmId/)
})
test('AI input without a ready proposal blocks form submission and hides manual scope', () => {
  assert.match(page, /const awaitingAiProposal = \(subject !== 'stock' \|\| prompt\.trim\(\)\.length > 0 \|\| history\.length > 0\) && !proposal/)
  assert.match(page, /onSubmit=\{[^\n]+\|\| awaitingAiProposal\) return;/)
  assert.match(page, /disabled=\{!catalog.data\?\.enabled[^\n]+\|\| awaitingAiProposal\}/)
  assert.match(page, /\{!awaitingAiProposal && <div/)
  assert.match(page, /AI isteğini temizle, elle hazırla/)
  assert.match(page, /setPrompt\(''\); setConsent\(false\); setProposal\(null\)/)
})
test('conversation preserves choices, sends only prompts and codes and resets on firm change', () => {
  assert.match(page, /history: history\.map\(turn => \(\{ prompt: turn\.prompt, clarification: turn\.clarification \}\)\)/)
  assert.match(page, /setHistory\(previous => \[\.\.\.previous,/)
  assert.match(page, /setFirmId\(e.target.value\);[^\n]+setHistory\(\[\]\)/)
  assert.match(page, /history.length >= 8/)
  assert.match(page, /Bu rapor konuşmasındaki mesajlarımın/)
  assert.match(page, /Yeni rapor başlat/)
  const quick = page.slice(page.indexOf('aria-label="Hızlı yanıt seçenekleri"'), page.indexOf('Müşteri adı, adres'))
  assert.match(quick, /setPrompt\(answer\)/)
  assert.doesNotMatch(quick, /interpret.mutate/)
})
test('order source is permission scoped, resets conversation and keeps currency totals separate', () => {
  assert.match(page, /!hasPermission\('inventory.view'\) && !hasPermission\('orders.view'\)/)
  assert.match(page, /transmissionConfirmed: consent, firmId, subject/)
  assert.match(page, /setSubject\(e.target.value\); setPrompt\(''\); setHistory\(\[\]\); setProposal\(null\)/)
  assert.match(page, /result.currencyTotals\?\.map/)
  assert.match(page, /order_dates/)
  assert.match(page, /order_layout/)
  assert.match(page, /subject === 'stock' && <fieldset/)
})
test('dynamic plan is opt-in from server catalog and preserves the V1 fallback', () => {
  assert.match(page, /\(subject === 'stock' \|\| subject === 'orders' \|\| subject === 'stockMovements' \|\| subject === 'returns' \|\| subject === 'customers' \|\| subject === 'staffActivities' \|\| subject === 'productCards'\) && catalog.data\?\.dynamicEnabled === true/)
  assert.match(page, /dynamicMode \? \{ planVersion: 2 \} : \{\}/)
  assert.match(page, /data.status === 'ready' && dynamicMode && data.dynamicPlan/)
  assert.match(page, /const planAllowed = !dynamicPlan \|\| dynamicMode/)
  assert.match(page, /!awaitingAiProposal && planAllowed/)
  assert.match(page, /!planAllowed \|\| awaitingAiProposal\) return/)
  assert.match(page, /data.status === 'ready' && data.definition/)
  assert.match(page, /interpret.data.clarification === 'dynamic_layout'/)
  assert.match(page, /subject === 'stockMovements' \? 'Hareket tipine göre özet' : 'Sipariş durumuna göre özet'/)
})
test('dynamic preview shows source period, nested conditions, measures and ordering without execution', () => {
  assert.match(page, /definition.aggregate\?\.measures/)
  assert.match(page, /Dönem \(Türkiye saati\)/)
  assert.match(page, /dynamicSelection\?\.sort/)
  assert.match(page, /<PredicatePreview predicate=\{dynamicPlan.predicate\}/)
  assert.match(page, /Tüm koşullar \(VE\)/)
  assert.match(page, /İlişkili kayıt YOK \(erişebildiğiniz kayıtlar içinde\)/)
  assert.match(page, /predicate.children\?\.slice\(0, 16\).map/)
  assert.match(page, /if \(depth > 6\)/)
  assert.doesNotMatch(page, /dangerouslySetInnerHTML/)
})
test('dynamic grid uses selected aggregate columns and does not offer impossible global search', () => {
  assert.match(page, /dynamicPlan \? \{ type: metrics.includes\(id\) \? 'number' : 'text' \}/)
  assert.match(page, /search=\{dynamicPlan && !canSearch \? false/)
  assert.match(page, /key: id, header: label\(id\)/)
  assert.match(page, /definition: JSON.parse\(submitted!.recipe\)/)
  assert.doesNotMatch(page, /rows\.slice|rows\.filter|rows\.sort|\.reduce\(/)
})
test('top-group preview distinguishes report membership from table filters', () => {
  assert.match(page, /top\?: number \| null/)
  assert.match(page, /dynamicSelection\?\.top != null/)
  assert.match(page, /detailPlan \? 'kayıt' : 'grup'/)
  assert.match(page, /listeye dışarıdan yeni grup eklemez/)
})
test('detail preview preserves column order and uses server metadata types without an AI rerun', () => {
  assert.match(page, /if \(submitted\?\.recipe !== next\) grid.mutate/)
  assert.match(page, /const dynamicPlan = 'source' in definition/)
  assert.doesNotMatch(page, /'aggregate' in definition/)
  assert.match(page, /definition.detail\?\.columns/)
  assert.match(page, /Detay kolonları:/)
  assert.match(page, /Her satır bir sipariştir/)
  assert.match(page, /fieldType\(id\) === 'date' \? 'date'/)
  assert.match(page, /fieldType\(id\) === 'number' \? 'number'/)
  assert.match(page, /dimensions.some\(id => fieldType\(id\) === 'text'\)/)
})

test('relative period requires explicit choice, hides stale result and shows server resolved dates', () => {
  assert.match(page, /value=\{dynamicPlan.period \?\? ''\}/)
  assert.match(page, /setProposal\(\{ \.\.\.dynamicPlan, period: event.target.value \|\| null \}\); run.reset\(\)/)
  for (const period of ['thisMonth', 'lastMonth', 'last30Days', 'last6Months'])
    assert.ok(page.includes(`value="${period}"`))
  assert.match(page, /result.resolvedPeriod.from/)
  assert.match(page, /result.resolvedPeriod.to/)
  assert.match(page, /koşullarda ayrıca yazılmış tarihler değişmez/)
})
